### ISSUE TITLE
APK Release on Github

### ISSUE THREAD

**Issue by meichthys** [flipreverse/FPCameraPhotoProxy#1]
@flipreverse Would it be possible too have an APK release on Gihtub so we can use tools like Obtainium to install it?it 
I've tried compiling apks myself but it generally doesn't go as smoothly as planned!

**Comment by flipreverse** [comment]
@meichthys I'll have a look at it. I didn't do that before. So, it might take some time.

**Comment by meichthys** [comment]
OK cool. Even just an upload of the apk would be great for now. No need to implement an automated github action or anything.

**Comment by flipreverse** [comment]
@meichthys I'm sorry. I now managed to create a release.
